data = [
{"toaq":"ba","type":"illocution","en":"imperative"},
{"toaq":"baq","type":"predicate","en":"___ is the generic collective entity composed of the things that share property ___; ___ are the things that ___, in general."},
{"toaq":"bai","type":"predicate","en":"___ builds/assembles/makes ___."},
{"toaq":"bao","type":"predicate","en":"___ is the colour white."},
{"toaq":"baogūi","type":"predicate","en":"___ is rice."},
{"toaq":"baorēo","type":"predicate","en":"___ is of white colour."},
{"toaq":"bu","type":"predicate","en":"___ is not the case / is false; ___ does not satisfy property ___."},
{"toaq":"bubōqkīu","type":"predicate","en":"___ is inevitable."},
{"toaq":"buhūokīu","type":"predicate","en":"___ is inaudible."},
{"toaq":"bukāqkīu","type":"predicate","en":"___ is invisible."},
{"toaq":"bu dải","type":"predicate","en":"___ is impossible."},
{"toaq":"bu tỉ","type":"predicate","en":"___ is away; ___ is not present at ___."},
{"toaq":"bumērāq","type":"predicate","en":"___ is a boomerang."},
{"toaq":"burūaq","type":"predicate","en":"___ lies / asserts untruth ___."},
{"toaq":"butīmēo","type":"predicate","en":"___ misses ___; ___ is sad that ___ is not there."},
{"toaq":"buq","type":"predicate","en":"___ is a mouth."},
{"toaq":"buqlūo","type":"predicate","en":"___ is a lip."},
{"toaq":"bua","type":"predicate","en":"___ inhabits ___."},
{"toaq":"buajīo","type":"predicate","en":"___ is a house (building for living in)."},
{"toaq":"buaq","type":"predicate","en":"___ fails to satisfy property ___."},
{"toaq":"buaq gải","type":"predicate","en":"___ misses ___; ___ fails to observe ___."},
{"toaq":"bui","type":"predicate","en":"___ is outside of ___."},
{"toaq":"buidūo","type":"predicate","en":"___ moves out of ___."},
{"toaq":"buifa","type":"predicate","en":"___ goes out of / exits ___."},
{"toaq":"buo","type":"predicate","en":"___ is ready to satisfy property ___."},
{"toaq":"buoq","type":"predicate","en":"___ is non-serious."},
{"toaq":"bue","type":"predicate","en":"___ is a home of ___."},

{"toaq":"buai","type":"predicate","en":"___ is long."},

{"toaq":"bi","type":"particle","en":"terminates prenex"},
{"toaq":"bidēo","type":"predicate","en":"___ is a video."},
{"toaq":"bikīnī","type":"predicate","en":"___ is a bikini."},
{"toaq":"birā","type":"predicate","en":"___ is beer."},
{"toaq":"biq","type":"predicate","en":"___ are a thousand in number."},
{"toaq":"bia","type":"predicate","en":"___ is sick/ill; ___ is sick/ill with ___."},
{"toaq":"biajīo","type":"predicate","en":"___ is a hospital."},
{"toaq":"biaq","type":"predicate","en":"___ is enough; ___ sufficiently satisfies property ___."},
{"toaq":"biu","type":"predicate","en":"___ is a tube."},
{"toaq":"bio","type":"predicate","en":"___ is a cup/glass."},

{"toaq":"bie","type":"predicate","en":"___ takes place after ___."},
{"toaq":"biejāo","type":"predicate","en":"___ takes place long after ___."},
{"toaq":"biejūi","type":"predicate","en":"___ takes place shortly after ___."},



{"toaq":"bo","type":"predicate","en":"___ has/possesses ___."},
{"toaq":"bohīaq","type":"predicate","en":"___ is poor/unwealthy."},
{"toaq":"bomīa","type":"predicate","en":"___ is rich/wealthy."},
{"toaq":"bonūa","type":"predicate","en":"___ takes possession of ___ from ___."},
{"toaq":"bone","type":"predicate","en":"___ is the amount of ___'s wealth."},
{"toaq":"bodōa","type":"predicate","en":"___ gives possession of ___ to ___."},
{"toaq":"boq","type":"predicate","en":"___ prevents ___."},


{"toaq":"peq","type":"predicate","en":"___ is a leaf/sheet."},
{"toaq":"peqbōe","type":"predicate","en":"___ is a sheet of paper."},
{"toaq":"boi","type":"predicate","en":"___ takes place from ___ onwards."},
{"toaq":"be","type":"predicate","en":"___ is an infant; ___ is a baby."},
{"toaq":"bebē","type":"predicate","en":"___ is a baby."},
{"toaq":"beq","type":"predicate","en":"___ is an extrusion/swelling/convex."},
{"toaq":"bea","type":"predicate","en":"___ is a knee/elbow/knuckle."},
{"toaq":"beaq","type":"predicate","en":"___ is a stick/pole."},
{"toaq":"beo","type":"predicate","en":"___ changes; ___ changes in property ___."},

{"toaq":"ca","type":"predicate","en":"___ physically causes ___ to be the case."},
{"toaq":"ca pủaq","type":"predicate","en":"___ breaks/splits/separates ___."},
{"toaq":"caq","type":"predicate","en":"___ conducts/directs/manages ___."},
{"toaq":"caqchūo","type":"predicate","en":"___ is a controller (instrument for controlling) for ___."},
{"toaq":"caqgīo","type":"predicate","en":"___ is a traffic light."},
{"toaq":"cai","type":"predicate","en":"___ is strong."},
{"toaq":"caidūa","type":"predicate","en":"___ is certain that ___ is the case."},
{"toaq":"cao","type":"predicate","en":"___ is a season."},
{"toaq":"cu","type":"linking word","en":"linking word: 3rd argument place"},
{"toaq":"cutāo","type":"predicate","en":"___ spits."},

{"toaq":"cua","type":"predicate","en":"___ responds to satisfying property ___ by satisfying property ___."},
{"toaq":"cuakūq","type":"predicate","en":"___ responds ___ to ___."},
{"toaq":"cuaq","type":"predicate","en":"___ is the concept/idea of satisfying property ___."},
{"toaq":"cuaq dẻ","type":"argument phrase","en":"⁕the concept of beauty⁕"},
{"toaq":"cui","type":"predicate","en":"___ is the colour magenta."},
{"toaq":"cuirēo","type":"predicate","en":"___ is magenta-coloured."},
{"toaq":"cuo","type":"predicate","en":"___ assumes that ___ is the case."},

{"toaq":"cue","type":"predicate","en":"___ reigns over ___."},
{"toaq":"cuefūai","type":"predicate","en":"___ is a government; ___ is a government of ___."},

{"toaq":"cuai","type":"predicate","en":"___ is wet."},
{"toaq":"cuao","type":"predicate","en":"___ is beyond ___ in property ___."},


{"toaq":"cia","type":"predicate","en":"___ lacks property ___."},

{"toaq":"ciu","type":"predicate","en":"___ excretes ___."},
{"toaq":"ciurīaq","type":"predicate","en":"___ is a toilet."},
{"toaq":"ciusē","type":"predicate","en":"___ is an excretion."},
{"toaq":"cio","type":"predicate","en":"___ is adolescent/pubescent."},

{"toaq":"cie","type":"predicate","en":"___ is a fish."},



{"toaq":"co","type":"quantifier","en":"quantifier: how many"},

{"toaq":"coa","type":"predicate","en":"___ is a bridge."},


{"toaq":"coe","type":"predicate","en":"___ is joined/connected to ___."},
{"toaq":"coetūa","type":"predicate","en":"___ joins ___ with ___."},
{"toaq":"ce","type":"predicate","en":"___ is a node/station/port."},



{"toaq":"ceo","type":"predicate","en":"___ begins/starts to occur; ___ begins/starts to satisfy property ___."},

{"toaq":"cha","type":"predicate","en":"___ takes place in way/form ___."},
{"toaq":"chaq","type":"predicate","en":"___ is a day."},
{"toaq":"chaqtū","type":"predicate","en":"___ happens every day; ___ is daily."},
{"toaq":"chai","type":"predicate","en":"___ is tea."},
{"toaq":"chao","type":"predicate","en":"___ is a vehicle."},
{"toaq":"chaotīeq","type":"predicate","en":"___ is a road."},
{"toaq":"chu","type":"predicate","en":"___ is a middle; ___ is the middle of ___."},
{"toaq":"chufāq","type":"predicate","en":"___ is ongoing; ___ is in the middle of taking place; ___ is ___ing."},
{"toaq":"chuq","type":"predicate","en":"___ eats; ___ eats ___."},
{"toaq":"chuqgūao","type":"predicate","en":"___ is a fork."},
{"toaq":"chuqkūai","type":"predicate","en":"___ is hungry."},
{"toaq":"chuqtīao","type":"predicate","en":"___ is edible."},
{"toaq":"chua","type":"predicate","en":"___ is a name of ___."},
{"toaq":"chuadōa","type":"predicate","en":"___ names/calls ___ name ___."},

{"toaq":"chui","type":"predicate","en":"___ is early."},
{"toaq":"chuihāq","type":"predicate","en":"___ is breakfast."},
{"toaq":"chuirīao","type":"predicate","en":"___ is dawn."},
{"toaq":"chuo","type":"predicate","en":"___ is a tool/utensil/resource/instrument for satisfying property ___."},

{"toaq":"chue","type":"predicate","en":"___ is a train/caravan/succession."},
{"toaq":"chuecē","type":"predicate","en":"___ is a train station."},

{"toaq":"chuai","type":"predicate","en":"___ is frozen."},
{"toaq":"chuaikēa","type":"predicate","en":"___ is a freezer."},
{"toaq":"chuaināo","type":"predicate","en":"___ is ice (frozen water)."},
{"toaq":"chuairūq","type":"predicate","en":"___ is hail."},
{"toaq":"chuairūqshūa","type":"predicate","en":"It hails; ___ hails; ___ hails onto ___."},
{"toaq":"Chủairūqshūa.","type":"phrase","en":"⁕It's hailing.⁕"},
{"toaq":"Shủa chúairūq.","type":"phrase","en":"⁕Hail is falling.⁕"},
{"toaq":"chuao","type":"predicate","en":"___ is a window."},
{"toaq":"chuaotīe","type":"predicate","en":"___ is a window cover."},
{"toaq":"chi","type":"predicate","en":"___ believe ___ to be the case / to be true."},
{"toaq":"chijīo","type":"predicate","en":"___ is a temple/church/sanctuary/synagogue/shrine."},

{"toaq":"chia","type":"predicate","en":"___ needs to satisfy property ___ to satisfy property ___."},
{"toaq":"chiaq","type":"predicate","en":"___ is conscious; ___ is aware of ___."},
{"toaq":"chiu","type":"predicate","en":"___ is the address/coordinates of ___."},
{"toaq":"chio","type":"predicate","en":"___ repeats ___ times."},

{"toaq":"chie","type":"predicate","en":"___ learns ___."},
{"toaq":"chiejīo","type":"predicate","en":"___ is a school."},

{"toaq":"chiai","type":"predicate","en":"___ is wrong/incorrect."},
{"toaq":"chiaitāo","type":"predicate","en":"___ errs; ___ makes mistake ___."},

{"toaq":"cho","type":"predicate","en":"___ likes ___."},
{"toaq":"chosōq","type":"predicate","en":"___ is the favourite of ___ among ___."},
{"toaq":"choq","type":"predicate","en":"___ uses ___ for ___."},
{"toaq":"choqgī","type":"predicate","en":"___ is useful for doing ___."},
{"toaq":"choqhūi","type":"predicate","en":"___ is useless/inconvenient for doing ___."},
{"toaq":"choqkīu","type":"predicate","en":"___ is usable (possible to use)"},
{"toaq":"choqtīao","type":"predicate","en":"___ is usable (fit for use)."},
{"toaq":"choa","type":"predicate","en":"___ utters ___."},
{"toaq":"choadēoq","type":"predicate","en":"___ talks to ___."},
{"toaq":"choalāq","type":"predicate","en":"___ is a voice."},
{"toaq":"choaq","type":"predicate","en":"___ is a guest; ___ is a guest of ___."},
{"toaq":"choaqjīo","type":"predicate","en":"___ is a hotel/guesthouse."},
{"toaq":"choi","type":"predicate","en":"___ is sharp."},
{"toaq":"choibeq","type":"predicate","en":"___ is a thorn."},
{"toaq":"choihua","type":"predicate","en":"___ is a thorn."},
{"toaq":"choe","type":"predicate","en":"___ takes place until ___."},
{"toaq":"che","type":"predicate","en":"___ is someone whose occupation it is to satisfy property ___."},
{"toaq":"che chỉetūa","type":"predicate","en":"___ is a teacher."},
{"toaq":"che giaqtāo","type":"predicate","en":"___ is a musician."},

{"toaq":"chea","type":"predicate","en":"___ is a hat."},
{"toaq":"chealīao","type":"predicate","en":"___ is a mushroom."},
{"toaq":"cheaq","type":"predicate","en":"___ is trusty/trusted to ___."},
{"toaq":"cheo","type":"predicate","en":"___ are in reciprocal relationship ___ with each other."},
{"toaq":"cheoq","type":"predicate","en":"___ is a bottle."},
{"toaq":"da","type":"illocution","en":"assertive illocution"},
{"toaq":"daq","type":"predicate","en":"___ is time."},
{"toaq":"daqfāi","type":"predicate","en":"___ occurs frequently/often."},
{"toaq":"dãqfāi","type":"adverb","en":"⁕often⁕"},
{"toaq":"daqfāo","type":"predicate","en":"___ is the end of ___; ___ is the point at which ___ ceases to be."},
{"toaq":"daqfīa","type":"predicate","en":"___ is previous to ___ in time."},
{"toaq":"daqkēa","type":"predicate","en":"___ is a clock."},
{"toaq":"daqlēi","type":"predicate","en":"___ is seldom/infrequent."},
{"toaq":"dãqlēi","type":"adverb","en":"⁕seldom⁕"},
{"toaq":"daqmīq","type":"predicate","en":"___ is eternal/forever."},
{"toaq":"daqmōa","type":"predicate","en":"___ is a moment."},
{"toaq":"daqsīao","type":"predicate","en":"___ is the beginning of ___; is the point at which ___ begins to be."},
{"toaq":"daqsīe","type":"predicate","en":"___ is following to ___ in time."},
{"toaq":"dai","type":"predicate","en":"___ is possible; ___ has the potential to satisfy property ___."},
{"toaq":"dãi","type":"adverb","en":"⁕maybe⁕, ⁕possibly⁕"},
{"toaq":"daichī","type":"predicate","en":"___ has hope that ___ is the case; ___ believes ___ can happen."},
{"toaq":"daisīo","type":"predicate","en":"___ is an idea."},
{"toaq":"dao","type":"predicate","en":"___ is information/data."},
{"toaq":"daosī","type":"predicate","en":"___ is interested in ___; ___ is curious about ___."},
{"toaq":"du","type":"predicate","en":"___ seems to be the case; ___ seems to satisfy property ___."},
{"toaq":"duq","type":"predicate","en":"___ habitually satisfies property ___."},
{"toaq":"dua","type":"predicate","en":"___ knows ___ to be the case / to be true."},
{"toaq":"duafūi","type":"predicate","en":"___ is obvious; ___ is obvious to ___."},
{"toaq":"dũafūi","type":"adverb","en":"⁕obviously⁕, ⁕clearly⁕, ⁕of course⁕"},
{"toaq":"duagī","type":"predicate","en":"___ is wise."},
{"toaq":"duahūi","type":"predicate","en":"___ is foolish."},
{"toaq":"duasūe","type":"predicate","en":"___ wants to know from ___ fact ___; ___ asks ___ fact ___."},
{"toaq":"duashāo","type":"predicate","en":"___ wonders about ___."},
{"toaq":"duashō","type":"predicate","en":"___ discovers / finds out ___."},

{"toaq":"dui","type":"predicate","en":"___ is too much ___; ___ satisfies property ___ too much to satisfy property ___."},
{"toaq":"duo","type":"predicate","en":"___ moves to ___ from ___."},
{"toaq":"duofūaq","type":"predicate","en":"___ is a movie."},
{"toaq":"duoq","type":"predicate","en":"___ is a bag/sack."},
{"toaq":"due","type":"predicate","en":"___ is correct."},
{"toaq":"dueq","type":"predicate","en":"___ is a field."},
{"toaq":"duai","type":"predicate","en":"___ must satisfy property ___."},
{"toaq":"duao","type":"predicate","en":"___ is sweet/sugary."},
{"toaq":"duaohēa","type":"predicate","en":"___ is a piece of candy."},
{"toaq":"di","type":"predicate","en":"___ is allowed to satisfy property ___."},

{"toaq":"dia","type":"predicate","en":"___ decreases in how much it satisfies property ___."},
{"toaq":"diaq","type":"predicate","en":"___ occurs at regular intervals; ___ satisfies property ___ at regular intervals."},
{"toaq":"diaqkūe","type":"predicate","en":"___ is a journal/periodical/newspaper."},
{"toaq":"diu","type":"predicate","en":"___ is the branch of knowledge that studies ___."},
{"toaq":"dio","type":"predicate","en":"___ is a daytime."},
{"toaq":"diochū","type":"predicate","en":"___ is a noon."},
{"toaq":"diochūhāq","type":"predicate","en":"___ is a lunch."},
{"toaq":"diofāo","type":"predicate","en":"___ is an evening."},
{"toaq":"diosiao","type":"predicate","en":"___ is a morning."},

{"toaq":"die","type":"predicate","en":"___ suggests ___."},


{"toaq":"diao","type":"predicate","en":"___ is a drop."},
{"toaq":"do","type":"predicate","en":"variable X"},
{"toaq":"doq","type":"predicate","en":"___ is short."},
{"toaq":"doa","type":"predicate","en":"___ gives ___ to ___."},
{"toaq":"doaq","type":"predicate","en":"___ is a settlement/town/village/city."},
{"toaq":"doaqpāq","type":"predicate","en":"___ is a district."},

{"toaq":"doe","type":"predicate","en":"___ functions/performs property ___."},
{"toaq":"de","type":"predicate","en":"___ is beautiful."},
{"toaq":"deq","type":"predicate","en":"___ is able / has the ability to satisfy property ___."},
{"toaq":"dea","type":"predicate","en":"___ hits/punches/kicks ___."},
{"toaq":"deaq","type":"predicate","en":"___ is a floor."},
{"toaq":"deaqkōi","type":"predicate","en":"___ crawls."},
{"toaq":"deo","type":"predicate","en":"___ is a child."},
{"toaq":"deoq","type":"predicate","en":"___ communicates with ___."},
{"toaq":"fa","type":"predicate","en":"___ goes to ___ from ___."},
{"toaq":"farīkā","type":"predicate","en":"___ is Africa."},
{"toaq":"faq","type":"predicate","en":"___ happens / takes place."},
{"toaq":"fai","type":"predicate","en":"___ is frequent/common in property ___."},
{"toaq":"fao","type":"predicate","en":"___ is an end/ending; ___ is an end/ending of ___."},
{"toaq":"fu","type":"predicate","en":"___ is a biological offspring of ___."},
{"toaq":"fuq","type":"predicate","en":"___ is an article of clothing / garment / dress."},
{"toaq":"fua","type":"predicate","en":"___ is an item of furniture."},
{"toaq":"fuaq","type":"predicate","en":"___ is an image / a picture."},
{"toaq":"fuaqkāi","type":"predicate","en":"___ draws image ___ on ___."},
{"toaq":"fuaqkēa","type":"predicate","en":"___ is a photo-camera."},
{"toaq":"fui","type":"predicate","en":"Satisfying property ___ is easy for ___."},
{"toaq":"fuo","type":"predicate","en":"___ touches ___ (non-somatic); ___ is in contact with ___."},

{"toaq":"fue","type":"predicate","en":"___ are a hundred in number."},

{"toaq":"fuai","type":"predicate","en":"___ is a committee."},



{"toaq":"fia","type":"predicate","en":"___ is previous to ___ in sequence ___; ___ precedes ___ in sequence ___."},

{"toaq":"fiu","type":"predicate","en":"___ is shallow."},


{"toaq":"fie","type":"predicate","en":"___ is ugly."},
{"toaq":"fieq","type":"predicate","en":"___ creates/invents ___."},



{"toaq":"fotō","type":"predicate","en":"___ is a photograph."},
{"toaq":"foq","type":"predicate","en":"___ is a telephone."},
{"toaq":"foqdēoq","type":"predicate","en":"___ talks on the phone with ___."},
{"toaq":"foa","type":"predicate","en":"___ feels ___ (good or bad); ___ is ___ (ill or well)."},
{"toaq":"foaq","type":"predicate","en":"___ is comfortable; ___ feels comfort; ___ feels comfort in satisfying property ___."},
{"toaq":"foaqfūi","type":"predicate","en":"___ is convenient; ___ is comfortably easy."},
{"toaq":"foi","type":"predicate","en":"___ is boring/dull."},
{"toaq":"fe","type":"predicate","en":"___ are five in number."},

{"toaq":"fea","type":"predicate","en":"___ endures ___."},

{"toaq":"fei","type":"predicate","en":"___ is angry/mad."},
{"toaq":"feo","type":"predicate","en":"___ is a direction."},

{"toaq":"ga","type":"end-conversion","en":"terminates conversion via predicalizer."},
{"toaq":"gaq","type":"predicate","en":"___ accompanies / is with ___ in property ___."},
{"toaq":"gai","type":"predicate","en":"___ senses/observes ___."},
{"toaq":"gaipūa","type":"predicate","en":"___ enjoys sensing/observing ___."},
{"toaq":"gao","type":"predicate","en":"___ is above ___."},
{"toaq":"gaodūo","type":"predicate","en":"___ moves upwards."},
{"toaq":"gaokōi","type":"predicate","en":"___ climbs."},
{"toaq":"gaopāq","type":"predicate","en":"___ is the top of ___."},
{"toaq":"gu","type":"predicate","en":"___ are two in number."},
{"toaq":"gulīaq","type":"predicate","en":"___ is a pair/couple."},
{"toaq":"guchīo","type":"predicate","en":"___ happens twice / two times."},
{"toaq":"gupāq","type":"predicate","en":"___ is a half."},
{"toaq":"gusīoq","type":"predicate","en":"___ is a bicycle/bike."},
{"toaq":"guq","type":"predicate","en":"___ is below/underneath ___."},
{"toaq":"guqdūo","type":"predicate","en":"___ moves downwards."},
{"toaq":"guqpāq","type":"predicate","en":"___ is the bottom of ___."},
{"toaq":"gua","type":"predicate","en":"___ is a country."},
{"toaq":"guaq","type":"predicate","en":"___ is land/terrain."},
{"toaq":"guaqnāo","type":"predicate","en":"___ is a lake."},
{"toaq":"gui","type":"predicate","en":"___ is grain/cereal."},
{"toaq":"guo","type":"predicate","en":"___ is a repetition/instance of ___."},
{"toaq":"guosa","type":"predicate","en":"___ happens sometimes."},
{"toaq":"guosia","type":"predicate","en":"___ happens never."},
{"toaq":"guoq","type":"predicate","en":"___ is an anus."},
{"toaq":"gue","type":"predicate","en":"___ is curved/bent."},

{"toaq":"guai","type":"predicate","en":"___ works in satisfying property ___."},
{"toaq":"guairīaq","type":"predicate","en":"___ is a work place / office."},
{"toaq":"guao","type":"predicate","en":"___ is a furcation/fork/intersection/junction."},
{"toaq":"gi","type":"predicate","en":"___ is good."},
{"toaq":"Gỉ chảq ba.","type":"phrase","en":"⁕Good day!⁕"},
{"toaq":"Gỉ dỉochū ba.","type":"phrase","en":"⁕Good morning!⁕"},
{"toaq":"Gỉ nủaq ba.","type":"phrase","en":"⁕Good night!⁕"},
{"toaq":"gicīa","type":"predicate","en":"___ is free of property ___; ___ not having property ___ is good."},
{"toaq":"gidāitūe","type":"predicate","en":"___ is an opportunity."},
{"toaq":"ginūe","type":"predicate","en":"___ promises to ___ to satisfy property ___, which is good for the latter."},
{"toaq":"ginēq","type":"predicate","en":"___ is fortunate for ___."},
{"toaq":"gitā","type":"predicate","en":"___ is a guitar."},
{"toaq":"giq","type":"predicate","en":"___ satisfies with reversed polarity property ___."},
{"toaq":"giq gỉ","type":"predicate","en":"___ is ungood."},
{"toaq":"gia","type":"predicate","en":"___ is a ribbon/tape/strip/stripe."},
{"toaq":"giaq","type":"predicate","en":"___ is music."},
{"toaq":"giaqchūo","type":"predicate","en":"___ is a musical instrument."},
{"toaq":"giu","type":"predicate","en":"___ is a line."},
{"toaq":"gio","type":"predicate","en":"___ is light."},
{"toaq":"giocīa","type":"predicate","en":"___ is dark (without light)."},
{"toaq":"giofūaq","type":"predicate","en":"___ is a photograph."},
{"toaq":"giohīaq","type":"predicate","en":"___ is dark (poorly illuminated)."},
{"toaq":"giokēa","type":"predicate","en":"___ is a lamp."},
{"toaq":"giomīa","type":"predicate","en":"___ is bright."},

{"toaq":"gie","type":"predicate","en":"___ is an arm."},
{"toaq":"giebēa","type":"predicate","en":"___ is an elbow."},
{"toaq":"giejēoq","type":"predicate","en":"___ is an armpit."},
{"toaq":"gieshīo","type":"predicate","en":"___ is a shoulder."},


{"toaq":"giao","type":"predicate","en":"___ is dry."},
{"toaq":"go","type":"linking word","en":"linking word, indicates that the following argument fills the second argument place of the predicate."},

{"toaq":"goa","type":"predicate","en":"___ is space/room."},
{"toaq":"goafāi","type":"predicate","en":"___ is widespread/common."},
{"toaq":"goajāo","type":"predicate","en":"___ is spatially far away from ___."},
{"toaq":"goaq","type":"predicate","en":"___ is smooth/even."},
{"toaq":"goi","type":"predicate","en":"___ treats/doctors ___."},
{"toaq":"ge","type":"predicate","en":"___ is a stimulus."},
{"toaq":"geq","type":"predicate","en":"___ meets ___."},
{"toaq":"geqkūai","type":"predicate","en":"___ misses ___; ___ hungers to meet ___ (again)."},
{"toaq":"geqsīa","type":"predicate","en":"___ is alone."},
{"toaq":"gea","type":"predicate","en":"___ is high."},
{"toaq":"geajēaqkēa","type":"predicate","en":"___ is a lift."},
{"toaq":"geanūa","type":"predicate","en":"___ lifts up ___."},
{"toaq":"geaq","type":"predicate","en":"___ is dirty/unclean/contaminated."},

{"toaq":"geo","type":"predicate","en":"___ is old."},
{"toaq":"geonē","type":"predicate","en":"___ is the age of ___."},

{"toaq":"ha","type":"interjection","en":"laughter"},
{"toaq":"hasīa","type":"predicate","en":"___ is Asia."},
{"toaq":"haq","type":"predicate","en":"___ is food."},
{"toaq":"haqbāi","type":"predicate","en":"___ prepares food / cooks."},
{"toaq":"haqbāisē","type":"predicate","en":"___ is a meal; ___ is prepared food."},
{"toaq":"haqdōa","type":"predicate","en":"___ feeds ___ to ___."},
{"toaq":"haqhūa","type":"predicate","en":"___ is a stomach."},
{"toaq":"haqrīai","type":"predicate","en":"___ is a plate/dish."},
{"toaq":"hai","type":"predicate","en":"___ is already the case; ___ already satisfies property ___."},
{"toaq":"hao","type":"predicate","en":"the salient predicate"},
{"toaq":"hu","type":"vocative","en":"vocative"},
{"toaq":"hushō","type":"predicate","en":"___ becomes quiet/silent; ___ hushes."},

{"toaq":"hua","type":"predicate","en":"___ is a body part."},
{"toaq":"huaq","type":"predicate","en":"___ is more than ___ in property ___."},
{"toaq":"huaq gỉ","type":"predicate","en":"___ is better than ___."},
{"toaq":"huaq hủi","type":"predicate","en":"___ is worse than ___."},
{"toaq":"huaq pủi","type":"predicate","en":"___ are more numerous than ___."},
{"toaq":"huaqchō","type":"predicate","en":"___ prefers ___ over ___."},
{"toaq":"hui","type":"predicate","en":"___ is bad."},
{"toaq":"huicīa","type":"predicate","en":"___ is lacking in that does not satisfy property ___; ___ lacking property ___ is bad."},
{"toaq":"huilīe","type":"predicate","en":"___ suffers from experiencing property ___."},
{"toaq":"huinūa","type":"predicate","en":"___ threatens ___ with satisfying property ___."},
{"toaq":"huinēq","type":"predicate","en":"___ is unfortunate for ___."},
{"toaq":"huo","type":"predicate","en":"___ is auditory; ___ pertains to the sense of hearing/audition."},
{"toaq":"huogāi","type":"predicate","en":"___ hears ___."},
{"toaq":"huogī","type":"predicate","en":"___ sounds good; ___ sounds good to ___."},
{"toaq":"huohūa","type":"predicate","en":"___ is an ear."},
{"toaq":"huokīu","type":"predicate","en":"___ is audible."},
{"toaq":"huosī","type":"predicate","en":"___ listens to ___."},



{"toaq":"huai","type":"predicate","en":"___ scoops ___ out of ___."},
{"toaq":"huaichūo","type":"predicate","en":"___ is a spoon."},
{"toaq":"huao","type":"predicate","en":"___ is loose."},
{"toaq":"hi","type":"quantifier","en":"which?"},


{"toaq":"hiaq","type":"predicate","en":"___ is poor in property ___."},
{"toaq":"hiu","type":"predicate","en":"___ is a river."},
{"toaq":"hio","type":"predicate","en":"___ greets ___."},
{"toaq":"Hỉo ka.","type":"phrase","en":"⁕hello⁕, ⁕bye⁕"},

{"toaq":"hie","type":"predicate","en":"___ carries/bears/hauls ___."},


{"toaq":"hiao","type":"predicate","en":"___ harms/injures ___."},
{"toaq":"hiaodāi","type":"predicate","en":"___ is dangerous."},
{"toaq":"hiaorīeq","type":"predicate","en":"___ escapes from ___."},
{"toaq":"ho","type":"predicate","en":"___ is him/her/it / are them."},
{"toaq":"horā","type":"predicate","en":"___ is an hour."},
{"toaq":"hoq","type":"predicate","en":"___ is it (abstract)."},
{"toaq":"hoa","type":"predicate","en":"relative pronoun whose antecedent is the head of the containing relative clause"},
{"toaq":"hoaq","type":"predicate","en":"___ burns."},
{"toaq":"hoaqkēa","type":"predicate","en":"___ is a lighter."},
{"toaq":"hoi","type":"predicate","en":"___ are the aforementioned things; ___ is/are the aforementioned things that satisfy property ___."},
{"toaq":"hoe","type":"predicate","en":"___ is a sun."},

{"toaq":"Herōpā","type":"predicate","en":"___ is Europe."},
{"toaq":"heq","type":"predicate","en":"___ contains ___."},
{"toaq":"heqchūo","type":"predicate","en":"___ is a container."},
{"toaq":"heqmūo","type":"predicate","en":"___ is full; ___ is filled with ___."},
{"toaq":"heqshēa","type":"predicate","en":"___ is empty."},
{"toaq":"hea","type":"predicate","en":"___ is a piece/chunk; ___ is a piece/chunk of substance ___."},
{"toaq":"heaq","type":"predicate","en":"___ carries/holds ___."},
{"toaq":"hei","type":"predicate","en":"___ are ten in number."},
{"toaq":"heo","type":"predicate","en":"___ is different from ___; ___ differs from ___ in property ___."},
{"toaq":"heoq","type":"predicate","en":"___ is a waist."},
{"toaq":"heoqgīa","type":"predicate","en":"___ is a belt."},
{"toaq":"ja","type":"quantifier","en":"quantifier: lambda"},
{"toaq":"jakē","type":"predicate","en":"___ is a jacket."},
{"toaq":"jaq","type":"predicate","en":"___ is extreme; ___ is very/extremely ___."},
{"toaq":"jaq bủ","type":"predicate","en":"___ is not at all the case; ___ does not satisfy property ___ at all; ___ very much does not satisfy property ___."},
{"toaq":"jaqbīaq","type":"predicate","en":"___ is sufficiently the case for ___ to be the case; ___ is so much so that ___ is the case."},
{"toaq":"jaqgālā","type":"predicate","en":"___ is a jungle."},
{"toaq":"jaqjēq","type":"predicate","en":"___ is as much as ___ in property ___."},
{"toaq":"jaqnūi","type":"predicate","en":"___ is tiny."},
{"toaq":"jaqrēo","type":"predicate","en":"___ is not the same amount as ___ in property ___."},
{"toaq":"jaqsāo","type":"predicate","en":"___ is huge."},
{"toaq":"jai","type":"predicate","en":"___ is happy/glad/joyful."},
{"toaq":"jao","type":"predicate","en":"___ is far away from ___ in property ___."},
{"toaq":"jaokūq","type":"predicate","en":"___ is a telephone / walkie talkie."},
{"toaq":"ju","type":"free modifier","en":"begin incidental clause"},
{"toaq":"juq","type":"predicate","en":"___ gets/acquires property ___."},
{"toaq":"juqgī","type":"predicate","en":"___ benefits ___."},
{"toaq":"jua","type":"predicate","en":"___ is weird/strange/bizarre."},
{"toaq":"juaq","type":"predicate","en":"Even ___ is the case; even ___ satisfies property ___."},
{"toaq":"jui","type":"predicate","en":"___ is near ___ in property ___."},

{"toaq":"juoq","type":"predicate","en":"___ should satisfy property ___."},
{"toaq":"jue","type":"predicate","en":"___ is a month."},
{"toaq":"juedīaq","type":"predicate","en":"___ occurs monthly."},

{"toaq":"juai","type":"predicate","en":"___ is serious/earnest."},
{"toaq":"juao","type":"predicate","en":"___ is a rule/law."},
{"toaq":"juaochīai","type":"predicate","en":"___ is illegal; ___ breaks rule ___; ___ is against law ___."},
{"toaq":"juaodūe","type":"predicate","en":"___ is legal; ___ is according to rule/law ___."},
{"toaq":"ji","type":"predicate","en":"___ is me / the speaker."},
{"toaq":"jiq","type":"predicate","en":"___ exists / is real/actual."},
{"toaq":"jiqdūa","type":"predicate","en":"___ knows that ___ exists."},
{"toaq":"jia","type":"predicate","en":"___ will happen."},
{"toaq":"jiachāq","type":"predicate","en":"___ is tomorrow; ___ is the day after today."},
{"toaq":"jiajāo","type":"predicate","en":"___ will happen a long time from now."},
{"toaq":"jiajūi","type":"predicate","en":"___ will happen in a short time from now."},
{"toaq":"jiashāo","type":"predicate","en":"___ hopes that ___ will be the case."},
{"toaq":"jiaq","type":"predicate","en":"___ is a world."},
{"toaq":"jiaqtū","type":"predicate","en":"___ is the universe."},
{"toaq":"jiu","type":"predicate","en":"___ is born."},
{"toaq":"jiuchāq","type":"predicate","en":"___ is a birthday of ___."},
{"toaq":"jio","type":"predicate","en":"___ is a building."},
{"toaq":"jioq","type":"predicate","en":"___ calculates ___."},
{"toaq":"jioqkēa","type":"predicate","en":"___ is a computer."},
{"toaq":"jie","type":"predicate","en":"___ is as ___ deems/judges/evaluates things to be."},
{"toaq":"Jảq dẻ báq rủa jìe hó da.","type":"phrase","en":"⁕Flowers are very beautiful to them.⁕"},
{"toaq":"jieq","type":"predicate","en":"___ is a tip / pointed end."},
{"toaq":"jiai","type":"predicate","en":"___ grasps/holds ___."},
{"toaq":"jiaikōi","type":"predicate","en":"___ climbs."},
{"toaq":"jiainūa","type":"predicate","en":"___ takes/removes ___ from ___."},
{"toaq":"jiao","type":"predicate","en":"___ is a god."},
{"toaq":"jiaojīo","type":"predicate","en":"___ is a temple/church/sanctuary/synagogue/shrine."},
{"toaq":"jo","type":"predicate","en":"___ are four in number."},
{"toaq":"jolīaq","type":"predicate","en":"___ is a quartet."},
{"toaq":"joq","type":"predicate","en":"___ is main/chief among ___."},
{"toaq":"joqdōaq","type":"predicate","en":"___ is a capital city of ___."},
{"toaq":"joqhūa","type":"predicate","en":"___ is a head (body part)."},
{"toaq":"joqshāq","type":"predicate","en":"___ is a face."},
{"toaq":"joa","type":"predicate","en":"___ is a week."},
{"toaq":"joachāq","type":"predicate","en":"___ is a weekday (day of the week)."},
{"toaq":"joachū","type":"predicate","en":"___ is during the week (not during a weekend)."},
{"toaq":"joadīaq","type":"predicate","en":"___ occurs weekly."},
{"toaq":"joafāo","type":"predicate","en":"___ is a weekend."},
{"toaq":"joaq","type":"predicate","en":"___ is a leader of ___."},

{"toaq":"joe","type":"predicate","en":"___ is skilled at satisfying property ___."},
{"toaq":"joetāo","type":"predicate","en":"___ practices skill ___."},
{"toaq":"je","type":"sentence prefix","en":"begin new sentence"},
{"toaq":"jeq","type":"predicate","en":"___ is the same as ___ in property ___."},
{"toaq":"jeqshūaq","type":"predicate","en":"___ copies ___; ___ produces an object identical to ___."},
{"toaq":"jeqtū","type":"predicate","en":"___ is identical to ___."},
{"toaq":"jea","type":"predicate","en":"___ buys ___ from ___."},
{"toaq":"jeajīo","type":"predicate","en":"___ is a mall."},
{"toaq":"jearīaq","type":"predicate","en":"___ is a market."},
{"toaq":"jeaq","type":"predicate","en":"___ increases in how much it satisfies property ___."},
{"toaq":"jeaq gỉ","type":"predicate","en":"___ improves / gets better."},
{"toaq":"jeaq tỉjūi","type":"predicate","en":"___ increases in its proximity to ___."},
{"toaq":"jeaqcāo","type":"predicate","en":"___ is spring (season)."},
{"toaq":"jei","type":"predicate","en":"___ is a digit/toe/finger."},
{"toaq":"jeo","type":"predicate","en":"___ is true / is the case; ___ satisfies property ___."},
{"toaq":"jeohūaq","type":"predicate","en":"___ is rather the case than ___; ___ is more true than ___."},
{"toaq":"jeojūi","type":"predicate","en":"___ is almost the case; ___ almost satisfies property ___."},
{"toaq":"jeonūe","type":"predicate","en":"___ promises to ___ that ___ is the case."},

{"toaq":"ka","type":"illocution","en":"performative illocution"},
{"toaq":"kafē","type":"predicate","en":"___ is coffee."},
{"toaq":"kahā","type":"predicate","en":"___ coughs."},
{"toaq":"kaq","type":"predicate","en":"___ is visual/optical; ___ pertains to the sense of sight/vision."},
{"toaq":"kaqchūo","type":"predicate","en":"___ is an optical tool."},
{"toaq":"kaqgāi","type":"predicate","en":"___ sees ___."},
{"toaq":"kaqgī","type":"predicate","en":"___ looks good; ___ looks good to ___."},
{"toaq":"kaqhūa","type":"predicate","en":"___ is an eye."},
{"toaq":"kaqhūatīe","type":"predicate","en":"___ is an eyelid."},
{"toaq":"kaqkīu","type":"predicate","en":"___ is visible."},
{"toaq":"kaqnūo","type":"predicate","en":"___ dreams ___."},
{"toaq":"kaqsī","type":"predicate","en":"___ looks at ___."},
{"toaq":"kaqshīa","type":"predicate","en":"___ are glasses."},
{"toaq":"kai","type":"predicate","en":"___ writes ___ on ___."},
{"toaq":"kaifūa","type":"predicate","en":"___ is a desk."},
{"toaq":"kaikēa","type":"predicate","en":"___ is a type writer."},
{"toaq":"kaisē","type":"predicate","en":"___ is text/writing."},

{"toaq":"ku","type":"prefix","en":"marks focus"},
{"toaq":"kuq","type":"predicate","en":"___ says ___ to ___."},
{"toaq":"kua","type":"predicate","en":"___ is a room."},
{"toaq":"kuabūe","type":"predicate","en":"___ is an appartment/flat."},
{"toaq":"kuaq","type":"predicate","en":"___ expresses property ___."},
{"toaq":"kuaq kỉe","type":"predicate","en":"___ thanks ___."},
{"toaq":"Kủaq kỉe jí ka.","type":"phrase","en":"⁕Thank you⁕, ⁕I hereby express my gratitude⁕"},
{"toaq":"kuaq shẻo","type":"predicate","en":"___ apologizes to ___."},
{"toaq":"Kủaq shẻo jí ka.","type":"phrase","en":"⁕I apologize⁕, ⁕I hereby express that I'm sorry⁕"},
{"toaq":"kui","type":"predicate","en":"___ is the case because ___."},
{"toaq":"kùi","type":"preposition","en":"⁕because⁕"},
{"toaq":"kuitūe","type":"predicate","en":"___ is a reason why ___ is the case."},
{"toaq":"kuo","type":"predicate","en":"___ is the colour black."},
{"toaq":"kuorēo","type":"predicate","en":"___ is of black colour."},
{"toaq":"kuoq","type":"predicate","en":"___ is a bone."},
{"toaq":"kue","type":"predicate","en":"___ is a book."},
{"toaq":"kuejīo","type":"predicate","en":"___ is a library."},
{"toaq":"kueshūo","type":"predicate","en":"___ is a library."},

{"toaq":"kuai","type":"predicate","en":"___ hungers/urges/longs for property ___."},
{"toaq":"kuao","type":"predicate","en":"___ is the colour cyan."},
{"toaq":"kuaochāq","type":"predicate","en":"___ is a Friday."},
{"toaq":"kuaorēo","type":"predicate","en":"___ is of cyan colour."},
{"toaq":"ki","type":"end-parenthetical","en":"terminates parenthetical"},
{"toaq":"kiq","type":"predicate","en":"___ is a movie/film."},
{"toaq":"kiqjīo","type":"predicate","en":"___ is a cinema / movie theater."},
{"toaq":"kiqkēa","type":"predicate","en":"___ is a film camera."},
{"toaq":"kia","type":"predicate","en":"___ is the colour red."},
{"toaq":"kiachāq","type":"predicate","en":"___ is a Monday."},
{"toaq":"kiarēo","type":"predicate","en":"___ is of red colour."},
{"toaq":"kiaq","type":"predicate","en":"___ is a hair."},
{"toaq":"kiu","type":"predicate","en":"___ is ___able."},

{"toaq":"kioq","type":"predicate","en":"___ is a ball/sphere."},
{"toaq":"kie","type":"predicate","en":"___ is thankful/grateful to ___ for satisfying property ___."},
{"toaq":"kiekūq","type":"predicate","en":"___ says thanks to ___."},

{"toaq":"kiai","type":"predicate","en":"___ looks after ___; ___ takes care of ___."},
{"toaq":"kiao","type":"predicate","en":"___ is a doorway."},
{"toaq":"kiaotōq","type":"predicate","en":"___ is a door."},
{"toaq":"ko","type":"predicate","en":"___ is the xth among ___ where x is the cardinality of anything satisfying property ___ sorted by property ___."},
{"toaq":"ko shỉ","type":"predicate","en":"___ is the first among ___ sorted by property ___."},
{"toaq":"ko gủ","type":"predicate","en":"___ is the second among ___ sorted by property ___."},
{"toaq":"ko sảq","type":"predicate","en":"___ is the third among ___ sorted by property ___."},
{"toaq":"kopī","type":"predicate","en":"___ is a copy of ___."},
{"toaq":"kopīshūaq","type":"predicate","en":"___ copies ___."},
{"toaq":"koq","type":"predicate","en":"___ is rough/uneven."},
{"toaq":"koqpīutā","type":"predicate","en":"___ is a computer."},
{"toaq":"koa","type":"predicate","en":"___ is cold/cool."},
{"toaq":"koacāo","type":"predicate","en":"___ is winter."},
{"toaq":"koakēa","type":"predicate","en":"___ is a refridgerator."},
{"toaq":"koaq","type":"predicate","en":"___ is mature/ripe/full-grown/adult."},
{"toaq":"koaqlīq","type":"predicate","en":"___ is a woman (adult female)."},
{"toaq":"koaqnāq","type":"predicate","en":"___ is a man (adult male)."},
{"toaq":"koaqrēq","type":"predicate","en":"___ is an adult human."},
{"toaq":"koi","type":"predicate","en":"___ ambulates."},
{"toaq":"koitīeq","type":"predicate","en":"___ is a walking path."},
{"toaq":"koe","type":"predicate","en":"___ chooses ___ out of ___ for ___."},
{"toaq":"koemēa","type":"predicate","en":"___ is an option."},

{"toaq":"keq","type":"predicate","en":"___ are feces; ___ is excrement/shit/poo."},
{"toaq":"keqcīu","type":"predicate","en":"___ defecates/shits."},
{"toaq":"kea","type":"predicate","en":"___ is a machine/apparatus performing function ___."},
{"toaq":"keaq","type":"predicate","en":"___ is salty."},
{"toaq":"keo","type":"sentence prefix","en":"but/however"},

{"toaq":"la","type":"incidental","en":"begin meta clause; makes a comment about the containing sentence (text not content)."},
{"toaq":"laq","type":"predicate","en":"___ is a sound; ___ is audio."},
{"toaq":"laqcāi","type":"predicate","en":"___ is loud."},
{"toaq":"laqgīa","type":"predicate","en":"___ is an audio tape."},
{"toaq":"laqkūe","type":"predicate","en":"___ is an audiobook."},
{"toaq":"laqrūe","type":"predicate","en":"___ is a weak/low sound."},

{"toaq":"lao","type":"predicate","en":"___ waits for ___ to be the case."},
{"toaq":"lu","type":"predicatizer","en":"turn statement into predicate"},
{"toaq":"luq","type":"predicate","en":"___ is calm/silent."},
{"toaq":"luqmōe","type":"predicate","en":"___ is calm (emotionally)."},
{"toaq":"lua","type":"predicate","en":"___ is a story."},
{"toaq":"luaq","type":"predicate","en":"___ plays / has fun with / uses for entertainment ___."},
{"toaq":"lui","type":"predicate","en":"___ has taken place."},
{"toaq":"luine","type":"predicate","en":"___ is the age of ___; ___ is the time since ___ has taken place."},
{"toaq":"luo","type":"predicate","en":"___ is a family."},
{"toaq":"luoq","type":"predicate","en":"___ is in balance with ___."},
{"toaq":"lue","type":"predicate","en":"___ is the colour yellow."},
{"toaq":"luechāq","type":"predicate","en":"___ is a Wednesday."},
{"toaq":"luerēo","type":"predicate","en":"___ is of yellow colour."},
{"toaq":"lueq","type":"predicate","en":"___ serves ___ with property ___."},
{"toaq":"lueqchē","type":"predicate","en":"___ is a servant of ___ with property ___."},
{"toaq":"luai","type":"predicate","en":"___ is funny/comical."},
{"toaq":"luailūa","type":"predicate","en":"___ is a joke."},
{"toaq":"luao","type":"predicate","en":"___ is a lip (general sense)."},
{"toaq":"li","type":"predicatizer","en":"turn statement into property"},
{"toaq":"liq","type":"predicate","en":"___ is female."},
{"toaq":"liqdēo","type":"predicate","en":"___ is a girl."},
{"toaq":"liqfū","type":"predicate","en":"___ is a daughter (female biological offspring) of ___."},
{"toaq":"liqpāo","type":"predicate","en":"___ is a mother of ___; ___ acts as a mother towards ___."},
{"toaq":"liqpīa","type":"predicate","en":"___ is a sister of ___."},
{"toaq":"liqrōaq","type":"predicate","en":"___ is a biological mother of ___."},
{"toaq":"liqrēq","type":"predicate","en":"___ is a female human; ___ is a woman."},
{"toaq":"liqsēo","type":"predicate","en":"___ is a wife of ___."},
{"toaq":"lia","type":"predicate","en":"___ is beside ___; ___ is to the side of ___; ___ is next to ___."},
{"toaq":"liaq","type":"predicate","en":"___ is a ___-tuple."},
{"toaq":"liu","type":"predicate","en":"___ is light in weight."},
{"toaq":"lio","type":"predicate","en":"___ is left to the left of ___."},
{"toaq":"liodūo","type":"predicate","en":"___ moves leftwards."},
{"toaq":"liopāq","type":"predicate","en":"___ is the left part of ___."},

{"toaq":"lie","type":"predicate","en":"___ experiences satisfying property ___."},

{"toaq":"liai","type":"predicate","en":"___ swims."},
{"toaq":"liao","type":"predicate","en":"___ is a fungus/mushroom/mold."},

{"toaq":"Lojībāq","type":"predicate","en":"___ is the Lojban language."},
{"toaq":"loq","type":"predicate","en":"___ is hot/warm."},
{"toaq":"loqcāo","type":"predicate","en":"___ is summer."},
{"toaq":"loqkēa","type":"predicate","en":"___ is a heater."},
{"toaq":"loa","type":"predicate","en":"___ is the colour purple."},
{"toaq":"loachāq","type":"predicate","en":"___ is a Sunday."},
{"toaq":"loarēo","type":"predicate","en":"___ is of purple colour."},
{"toaq":"loaq","type":"predicate","en":"___ is a buttocks/ass/behind."},
{"toaq":"loi","type":"predicate","en":"___ hates ___."},
{"toaq":"le","type":"predicate","en":"___ is likely/probable."},
{"toaq":"lẽ","type":"adverb","en":"⁕probably⁕"},
{"toaq":"leq","type":"predicate","en":"___ is a tongue."},
{"toaq":"lea","type":"predicate","en":"___ is art."},
{"toaq":"leachē","type":"predicate","en":"___ is an artist."},
{"toaq":"leaq","type":"predicate","en":"___ is adjacent to ___ in property ___."},
{"toaq":"leaqbūe","type":"predicate","en":"___ is a neighbour of ___."},
{"toaq":"leaqfīa","type":"predicate","en":"___ immediately precedes ___ in sequence ___."},
{"toaq":"leaqsīe","type":"predicate","en":"___ immediately follows ___ in sequence ___; ___ is next after ___ in sequence ___."},
{"toaq":"lei","type":"predicate","en":"___ is rare in property ___."},
{"toaq":"leo","type":"predicate","en":"___ tries to satisfy property ___."},


{"toaq":"mamā","type":"predicate","en":"___ is mama (Mom, mommy, mum, mother)."},
{"toaq":"maq","type":"predicate","en":"___ is it (non-personal concrete)."},
{"toaq":"mai","type":"predicate","en":"___ loves ___."},
{"toaq":"maigāq","type":"predicate","en":"___ is a boyfriend/girlfriend/SO of ___."},
{"toaq":"mao","type":"predicate","en":"___ is also the case; ___ also satisfies property ___."},

{"toaq":"muq","type":"predicate","en":"___ is a hand."},
{"toaq":"muqdūoq","type":"predicate","en":"___ is a handbag."},
{"toaq":"muqdēa","type":"predicate","en":"___ punches ___."},
{"toaq":"muqfūa","type":"predicate","en":"___ is a glove."},
{"toaq":"muqjēi","type":"predicate","en":"___ is a finger."},
{"toaq":"muqjēibēa","type":"predicate","en":"___ is a knuckle."},
{"toaq":"mua","type":"predicate","en":"___ is an example of ___."},
{"toaq":"muaq","type":"predicate","en":"___ is dead."},
{"toaq":"muaqshō","type":"predicate","en":"___ dies."},
{"toaq":"muaqtūa","type":"predicate","en":"___ kills ___."},
{"toaq":"mui","type":"predicate","en":"___ is the meaning of ___;"},
{"toaq":"muidūa","type":"predicate","en":"___ understands the meaning of ___."},
{"toaq":"muo","type":"predicate","en":"___ is whole/complete in aspect ___."},
{"toaq":"muo gỉ","type":"predicate","en":"___ is perfect."},
{"toaq":"muotūa","type":"predicate","en":"___ mends ___; ___ makes ___ whole; ___ completes ___."},
{"toaq":"muoq","type":"predicate","en":"___ is made of ___."},


{"toaq":"muai","type":"predicate","en":"___ has an umami taste."},
{"toaq":"muao","type":"predicate","en":"___ is a tree."},
{"toaq":"muaogūaq","type":"predicate","en":"___ is a forest."},
{"toaq":"mi","type":"predicatizer","en":"turns following phrase X into predicate: ___ is/are the one(s) called X."},
{"toaq":"minū","type":"predicate","en":"___ is a minute."},
{"toaq":"miq","type":"predicate","en":"___ is infinite in property ___."},
{"toaq":"mia","type":"predicate","en":"___ is rich in property ___."},
{"toaq":"miaq","type":"predicate","en":"___ is the value of ___."},
{"toaq":"miaqgāi","type":"predicate","en":"___ appreciates/esteems ___."},
{"toaq":"miaqjīe","type":"predicate","en":"___ appreciates ___."},
{"toaq":"miu","type":"predicate","en":"___ opines/thinks that ___ is the case."},
{"toaq":"miujēq","type":"predicate","en":"___ agrees with ___ that ___ is the case."},
{"toaq":"mio","type":"predicate","en":"___ is the colour blue."},
{"toaq":"miochāq","type":"predicate","en":"___ is a Saturday."},
{"toaq":"miorēo","type":"predicate","en":"___ is of blue colour."},

{"toaq":"mie","type":"predicate","en":"___ lives / is alive."},
{"toaq":"miefēa","type":"predicate","en":"___ survives ___."},
{"toaq":"miehūa","type":"predicate","en":"___ is a heart."},

{"toaq":"miai","type":"predicate","en":"___ rhymes with ___."},
{"toaq":"miaisē","type":"predicate","en":"___ is a rhyme."},
{"toaq":"miao","type":"predicate","en":"___ is a moon."},
{"toaq":"mo","type":"text-quote","en":"begin full-text quote."},
{"toaq":"moq","type":"illocution","en":"interrogative illocution"},
{"toaq":"moa","type":"predicate","en":"___ is a point in ___."},
{"toaq":"moaq","type":"predicate","en":"___ remembers ___."},
{"toaq":"moaqchūo","type":"predicate","en":"___ is a mnemonic for remembering ___."},
{"toaq":"moaqshāi","type":"predicate","en":"___ forgets ___."},
{"toaq":"moaqsīo","type":"predicate","en":"___ is a memory."},
{"toaq":"moi","type":"predicate","en":"___ thinks / is having a thought; ___ thinks thought ___."},
{"toaq":"moihūa","type":"predicate","en":"___ is a brain."},
{"toaq":"moijōe","type":"predicate","en":"___ is clever/smart/witty/intelligent."},
{"toaq":"moilāo","type":"predicate","en":"___ hesitates."},
{"toaq":"moinīeq","type":"predicate","en":"___ is dumb/stupid/unintelligent."},
{"toaq":"moisī","type":"predicate","en":"___ ponders / concentrates mentally on ___."},
{"toaq":"moisē","type":"predicate","en":"___ is a thought."},
{"toaq":"moe","type":"predicate","en":"___ feels ___; ___ has emotion ___."},
{"toaq":"moerīaq","type":"predicate","en":"___ is a heart/emotional/spiritual center/core."},
{"toaq":"moehūa","type":"predicate","en":"___ is an organ of feeling/emotion (⁕heart⁕)."},
{"toaq":"me","type":"predicate","en":"___ is an aggregate of ___."},
{"toaq":"merīkā","type":"predicate","en":"___ is America (continent)."},

{"toaq":"mea","type":"predicate","en":"___ is among ___."},
{"toaq":"meajēq","type":"predicate","en":"___ is the same thing as ___."},
{"toaq":"meahēo","type":"predicate","en":"___ is different from ___; ___ is not the same thing as ___; ___ is something else than ___."},
{"toaq":"meakūq","type":"predicate","en":"___ mentions ___ to ___."},
{"toaq":"meaq","type":"predicate","en":"___ is a ship/boat/vessel."},
{"toaq":"meaqcē","type":"predicate","en":"___ is a harbour/haven."},
{"toaq":"mei","type":"predicate","en":"___ is a mountain/hill."},
{"toaq":"meirie","type":"predicate","en":"___ is a valley."},
{"toaq":"meo","type":"predicate","en":"___ is sad."},
{"toaq":"meoq","type":"predicate","en":"___ is slow; ___ slowly satisfies property ___."},
{"toaq":"meoqkōi","type":"predicate","en":"___ walks."},
{"toaq":"na","type":"terminator","en":"terminate statement"},
{"toaq":"narāq","type":"predicate","en":"___ is the colour orange."},
{"toaq":"narāqchāq","type":"predicate","en":"___ is a Tuesday."},
{"toaq":"narāqrēo","type":"predicate","en":"___ is of orange colour."},
{"toaq":"naq","type":"predicate","en":"___ is male."},
{"toaq":"naqdēo","type":"predicate","en":"___ is a boy."},
{"toaq":"naqfū","type":"predicate","en":"___ is a son (male biological offspring) of ___."},
{"toaq":"naqpāo","type":"predicate","en":"___ is a father of ___; acts as a father towards ___."},
{"toaq":"naqpīa","type":"predicate","en":"___ is a brother of ___."},
{"toaq":"naqrōaq","type":"predicate","en":"___ is a biological father of ___."},
{"toaq":"naqrēq","type":"predicate","en":"___ is a male human; ___ is a man."},
{"toaq":"naqsēo","type":"predicate","en":"___ is a husband of ___."},
{"toaq":"nai","type":"predicate","en":"___ happens now."},
{"toaq":"nao","type":"predicate","en":"___ is water."},
{"toaq":"naogūaq","type":"predicate","en":"___ is an island."},
{"toaq":"naokūa","type":"predicate","en":"___ is a bathroom."},
{"toaq":"naonīai","type":"predicate","en":"___ is an aquatic life form."},
{"toaq":"nu","type":"predicate","en":"___ is such / is like that."},
{"toaq":"nũ","type":"adverb","en":"⁕like this⁕, ⁕like that⁕"},
{"toaq":"nuq","type":"predicate","en":"___ is a snake."},
{"toaq":"nua","type":"predicate","en":"___ takes/removes property ___ from ___."},
{"toaq":"nuakōe","type":"predicate","en":"___ picks ___: ___ chooses and takes ___."},
{"toaq":"nuaq","type":"predicate","en":"___ is a night."},
{"toaq":"nuaqchū","type":"predicate","en":"___ is midnight."},
{"toaq":"nui","type":"predicate","en":"___ is small/little."},
{"toaq":"nuidōaq","type":"predicate","en":"___ is a town."},
{"toaq":"nuo","type":"predicate","en":"___ sleeps / is asleep."},
{"toaq":"nuofūq","type":"predicate","en":"___ is a pyjama."},
{"toaq":"nuofūa","type":"predicate","en":"___ is a bed."},
{"toaq":"nuokūa","type":"predicate","en":"___ is a bedroom."},
{"toaq":"nuokūai","type":"predicate","en":"___ is tired."},

{"toaq":"nue","type":"predicate","en":"___ promises/threatens to ___ to satisfy property ___."},

{"toaq":"nuai","type":"predicate","en":"___ is money."},
{"toaq":"nuaijīo","type":"predicate","en":"___ is a bank."},
{"toaq":"nuao","type":"predicate","en":"___ is an arch; ___ arches."},
{"toaq":"ni","type":"predicate","en":"___ is this/that."},
{"toaq":"nijāo","type":"predicate","en":"___ is that far away thing."},
{"toaq":"nijūi","type":"predicate","en":"___ is this nearby thing."},
{"toaq":"nichāq","type":"predicate","en":"___ is today."},
{"toaq":"nidāq","type":"predicate","en":"___ is the now."},
{"toaq":"ninūaq","type":"predicate","en":"___ is tonight."},
{"toaq":"niq","type":"predicate","en":"___ is new; ___ is new to ___."},
{"toaq":"niqgūo","type":"predicate","en":"___ happens again."},
{"toaq":"niqgūokūai","type":"predicate","en":"___ misses ___; ___ hungers for ___ to happen again."},
{"toaq":"niqdāo","type":"predicate","en":"___ are news."},
{"toaq":"niqdūa","type":"predicate","en":"___ discovers / finds out ___."},
{"toaq":"nia","type":"predicate","en":"___ is low."},
{"toaq":"niaq","type":"predicate","en":"___ is a year."},
{"toaq":"niaqdīaq","type":"predicate","en":"___ is annual."},
{"toaq":"niu","type":"predicate","en":"___ is a plant."},
{"toaq":"niubōe","type":"predicate","en":"___ is a leaf (of a plant)."},
{"toaq":"nio","type":"predicate","en":"___ is young."},
{"toaq":"niodē","type":"predicate","en":"___ is cute."},

{"toaq":"nie","type":"predicate","en":"___ is inside ___."},
{"toaq":"niefā","type":"predicate","en":"___ enters / goes inside ___."},
{"toaq":"nietūa","type":"predicate","en":"___ puts ___ inside ___."},
{"toaq":"nieq","type":"predicate","en":"___ is unskilled at satisfying property ___."},
{"toaq":"niai","type":"predicate","en":"___ is an animal."},
{"toaq":"niao","type":"predicate","en":"___ is snow."},
{"toaq":"niaoshūa","type":"predicate","en":"It snows; ___ snows; ___ snows onto ___."},
{"toaq":"Nỉaoshūa.","type":"phrase","en":"⁕It's snowing.⁕"},
{"toaq":"no","type":"predicate","en":"___ is in format/medium/genre ___."},
{"toaq":"Dẻoq súq nò hi tóaq moq?","type":"phrase","en":"⁕In what language are you communicating?⁕"},
{"toaq":"nò Fárāqsē","type":"phrase","en":"⁕in French⁕"},
{"toaq":"noq","type":"predicate","en":"___ is gustatory; ___ pertains to the sense of taste/gustation."},
{"toaq":"noqgāi","type":"predicate","en":"___ tastes ___."},
{"toaq":"noqgī","type":"predicate","en":"___ tastes good / is delicious; ___ tastes good / is delicious to ___."},
{"toaq":"noqhūi","type":"predicate","en":"___ tastes bad; ___ tastes bad to ___."},
{"toaq":"noqsī","type":"predicate","en":"___ listens to the taste of ___."},
{"toaq":"noa","type":"predicate","en":"Satisfying property ___ is difficult for ___."},
{"toaq":"noaq","type":"predicate","en":"___ reads ___ from ___."},
{"toaq":"noi","type":"predicate","en":"___ is pain."},
{"toaq":"noilīe","type":"predicate","en":"___ suffers / has pain."},

{"toaq":"neq","type":"predicate","en":"___ is determined by the luck/fortunate of ___."},
{"toaq":"nea","type":"predicate","en":"___ is wide/broad."},
{"toaq":"neaq","type":"predicate","en":"___ is sand."},
{"toaq":"neaqgūaq","type":"predicate","en":"___ is a desert."},
{"toaq":"neo","type":"predicate","en":"___ is on ___."},
{"toaq":"neoq","type":"predicate","en":"___ is a Mr./Mrs."},
{"toaq":"pa","type":"terminator","en":"terminate prenex and apply prenex arguments to predicate in order"},
{"toaq":"papā","type":"predicate","en":"___ is papa (Dad, daddy, father)."},
{"toaq":"patā","type":"predicate","en":"___ is a potato."},
{"toaq":"patī","type":"predicate","en":"___ is a party (gathering for entertainment, fun and socializing)."},
{"toaq":"paq","type":"predicate","en":"___ is a part of ___."},
{"toaq":"paqcīa","type":"predicate","en":"___ lacks part ___; ___ is missing part ___."},
{"toaq":"paqmūo","type":"predicate","en":"___ is whole/complete."},
{"toaq":"paqnūa","type":"predicate","en":"___ removes part ___ from ___."},
{"toaq":"paqtāo","type":"predicate","en":"___ takes part in ___; ___ participates in ___."},
{"toaq":"paqshāi","type":"predicate","en":"___ loses part ___."},
{"toaq":"pai","type":"predicate","en":"___ is a friend; ___ is a friend of ___."},
{"toaq":"paigī","type":"predicate","en":"___ is friendly towards ___."},
{"toaq":"pairūo","type":"predicate","en":"___ acts friendly/kindly towards ___."},
{"toaq":"pao","type":"predicate","en":"___ is a parent of ___; ___ acts parental towards ___; ___ raises ___."},
{"toaq":"pu","type":"predicate","en":"___ happened / occured / was the case."},
{"toaq":"pujāo","type":"predicate","en":"___ happened a long time ago."},
{"toaq":"pujūi","type":"predicate","en":"___ happened a short time ago."},
{"toaq":"puq","type":"predicate","en":"___ are more than one / multiple things."},
{"toaq":"puqhō","type":"predicate","en":"___ are them."},
{"toaq":"pua","type":"predicate","en":"___ enjoys satisfying property ___."},
{"toaq":"puaq","type":"predicate","en":"___ is somatic/tactile; ___ pertains to the sense of touch/somatosensation."},
{"toaq":"puaqgāi","type":"predicate","en":"___ touch feels ___."},
{"toaq":"puaqgī","type":"predicate","en":"___ is nice to the touch; ___ is nice to the touch of ___."},
{"toaq":"puaqsī","type":"predicate","en":"___ focuses on touch feeling ___."},
{"toaq":"pui","type":"predicate","en":"___ are many."},
{"toaq":"puijēq","type":"predicate","en":"___ are equal in number to ___; ___ and ___ are equinumerous."},
{"toaq":"puishō","type":"predicate","en":"___ multiplies."},
{"toaq":"puitūa","type":"predicate","en":"___ multiplies ___."},
{"toaq":"puipōqchāo","type":"predicate","en":"___ is a bus/omnibus."},


{"toaq":"pue","type":"predicate","en":"___ is a foot."},
{"toaq":"puebēa","type":"predicate","en":"___ is a knee."},
{"toaq":"puedēa","type":"predicate","en":"___ kicks ___."},
{"toaq":"puefūq","type":"predicate","en":"___ is a shoe."},
{"toaq":"puegāo","type":"predicate","en":"___ is a sock."},
{"toaq":"puejēi","type":"predicate","en":"___ is a toe."},
{"toaq":"pueshīo","type":"predicate","en":"___ is a hip."},


{"toaq":"puao","type":"predicate","en":"___ is a cloud."},
{"toaq":"pi","type":"predicate","en":"___ is urine/pee/piss."},
{"toaq":"picīu","type":"predicate","en":"___ urinates/pees/pisses."},
{"toaq":"pijāmā","type":"predicate","en":"___ is a pyjama."},

{"toaq":"pia","type":"predicate","en":"___ is a sibling of ___."},
{"toaq":"pianō","type":"predicate","en":"___ is a piano."},



{"toaq":"pie","type":"predicate","en":"___ drinks ___."},
{"toaq":"piekūai","type":"predicate","en":"___ is thirsty."},


{"toaq":"piao","type":"predicate","en":"___ is complicated/complex."},
{"toaq":"po","type":"predicatizer","en":"turns following phrase X into predicate: ___ is of X; ___ is associated with X."},
{"toaq":"pojī","type":"predicate","en":"___ is mine."},
{"toaq":"posūq","type":"predicate","en":"___ is yours."},
{"toaq":"pomāq","type":"predicate","en":"___ is its."},
{"toaq":"pohō","type":"predicate","en":"___ is his/hers."},
{"toaq":"posūqjī","type":"predicate","en":"___ is ours."},
{"toaq":"popūqjī","type":"predicate","en":"___ is ours."},
{"toaq":"popūqsūq","type":"predicate","en":"___ is yours."},
{"toaq":"popūqhō","type":"predicate","en":"___ is theirs."},
{"toaq":"poq","type":"predicate","en":"___ is a person."},
{"toaq":"poqmē","type":"predicate","en":"___ is a group of people."},
{"toaq":"poa","type":"predicate","en":"___ is closed/shut."},
{"toaq":"poaq","type":"predicate","en":"___ breaks/parts/splits."},
{"toaq":"poaqsē","type":"predicate","en":"___ is a shard/cullet."},

{"toaq":"poe","type":"predicate","en":"___ is apart/separate from ___ in property ___."},
{"toaq":"pe","type":"predicatizer","en":"turns following phrase X into predicate: ___ is X."},
{"toaq":"peq","type":"predicate","en":"___ is paper."},


{"toaq":"peo","type":"predicate","en":"___ passes through ___."},

{"toaq":"ra","type":"conjunction","en":"inclusive or"},
{"toaq":"radīo","type":"predicate","en":"___ pertains to radio transmission."},
{"toaq":"raq","type":"predicate","en":"___ pertains to / is about ___."},
{"toaq":"raqmōi","type":"predicate","en":"___ thinks about ___."},
{"toaq":"rai","type":"predicate","en":"___ is something."},
{"toaq":"raijēq","type":"predicate","en":"___ is the same thing as ___."},
{"toaq":"rao","type":"predicate","en":"___ happens at the same time as ___; ___ is simultaneous with ___."},
{"toaq":"rao sa rái","type":"prepositional phrase","en":"⁕some time⁕, ⁕at some point⁕"},
{"toaq":"rào sia dáqmōa","type":"prepositional phrase","en":"⁕never⁕, ⁕at no moment⁕"},
{"toaq":"rào tu dáqmōa","type":"prepositional phrase","en":"⁕always⁕, ⁕at every moment⁕"},
{"toaq":"rào tu cháq","type":"prepositional phrase","en":"⁕every day⁕"},
{"toaq":"ru","type":"conjunction","en":"and"},
{"toaq":"súq ru jí","type":"argument phrase","en":"⁕you and I⁕"},
{"toaq":"ruq","type":"predicate","en":"___ is rain."},
{"toaq":"ruqdīao","type":"predicate","en":"___ is a raindrop."},
{"toaq":"ruqnūao","type":"predicate","en":"___ is a rainbow."},
{"toaq":"ruqshūa","type":"predicate","en":"It rains; ___ rains; ___ rains onto ___."},
{"toaq":"Rủqshūa.","type":"phrase","en":"⁕It's raining.⁕"},
{"toaq":"rua","type":"predicate","en":"___ is a flower."},
{"toaq":"ruaq","type":"predicate","en":"___ asserts/claims ___ to be the case."},
{"toaq":"rui","type":"predicate","en":"___ is the colour gray."},
{"toaq":"ruirēo","type":"predicate","en":"___ is of gray colour."},
{"toaq":"ruo","type":"predicate","en":"___ behaves in way ___ (property); ___ conducts themselves in manner ___ (property)."},
{"toaq":"ruogī","type":"predicate","en":"___ is well-behaved/good/nice."},
{"toaq":"ruoq","type":"predicate","en":"___ is straight/linear."},
{"toaq":"rue","type":"predicate","en":"___ is weak/feeble."},
{"toaq":"rueq","type":"predicate","en":"___ is tight."},
{"toaq":"ruai","type":"predicate","en":"___ is royal/noble/aristocratic."},
{"toaq":"ruaichēa","type":"predicate","en":"___ is a crown."},
{"toaq":"ruaijōaq","type":"predicate","en":"___ is a king/queen."},
{"toaq":"ruailīqfū","type":"predicate","en":"___ is a princess."},
{"toaq":"ruaijōaq","type":"predicate","en":"___ is a prince."},
{"toaq":"ruao","type":"predicate","en":"___ forgives ___ for satisfying property ___."},

{"toaq":"riq","type":"predicate","en":"___ is the colour green."},
{"toaq":"riqchāq","type":"predicate","en":"___ is a Thursday."},
{"toaq":"riqrēo","type":"predicate","en":"___ is of green colour."},
{"toaq":"ria","type":"predicate","en":"___ is open."},
{"toaq":"riaq","type":"predicate","en":"___ is a place/site; ___ is the place/site of ___."},
{"toaq":"riu","type":"predicate","en":"___ returns to satisfying property ___."},
{"toaq":"riubēaq","type":"predicate","en":"___ is a boomerang."},
{"toaq":"riudūo","type":"predicate","en":"___ returns to ___; ___ moves back to ___."},
{"toaq":"riudōa","type":"predicate","en":"___ returns ___ to ___; ___ gives ___ back to ___."},
{"toaq":"riufā","type":"predicate","en":"___ returns to ___; ___ goes back to ___."},
{"toaq":"rio","type":"predicate","en":"___ is air."},
{"toaq":"riochāo","type":"predicate","en":"___ is an aircraft/plane."},
{"toaq":"rioq","type":"predicate","en":"___ is a type/kind of ___"},
{"toaq":"rie","type":"predicate","en":"___ is between/amidst/among ___ (plural)."},
{"toaq":"rieq","type":"predicate","en":"___ avoids/evades satisfying property ___."},
{"toaq":"riai","type":"predicate","en":"___ supports ___; ___ holds up ___."},
{"toaq":"riao","type":"predicate","en":"___ is a twilight/dawn/dusk/half-light/glimmering."},
{"toaq":"ro","type":"conjunction","en":"exclusive or"},
{"toaq":"roq","type":"predicate","en":"___ cries/weeps; ___ cries tears ___."},
{"toaq":"roqdīao","type":"predicate","en":"___ is a tear/teardrop."},
{"toaq":"roa","type":"predicate","en":"___ is natural."},
{"toaq":"rõa","type":"adverb","en":"⁕naturally⁕"},
{"toaq":"roajīaq","type":"predicate","en":"___ is nature."},
{"toaq":"roaq","type":"predicate","en":"___ is a biological parent of ___."},
{"toaq":"roi","type":"conjunction","en":"plural and"},
{"toaq":"roe","type":"predicate","en":"___ is healthy."},
{"toaq":"roeshō","type":"predicate","en":"___ recovers; ___ becomes healthy."},

{"toaq":"req","type":"predicate","en":"___ is a human."},
{"toaq":"reqsīu","type":"predicate","en":"___ is humanoid/human-like."},
{"toaq":"rea","type":"predicate","en":"___ is a border/edge of ___."},
{"toaq":"reaq","type":"predicate","en":"___ lies on ___; ___ reclines on ___."},
{"toaq":"rei","type":"predicate","en":"___ is around ___; ___ surrounds ___."},
{"toaq":"reo","type":"predicate","en":"___ is coloured; ___ is of colour ___."},
{"toaq":"Chỏ jí ní rẻo.","type":"phrase","en":"⁕I like this colour.⁕"},
{"toaq":"Rẻo ní hirái moq?","type":"phrase","en":"⁕What colour is this?⁕, ⁕What colour does this have?⁕"},
{"toaq":"reosīa","type":"predicate","en":"___ is colourless."},
{"toaq":"reoq","type":"predicate","en":"___ is late."},
{"toaq":"reoqhāq","type":"predicate","en":"___ is dinner (late/evening meal)."},
{"toaq":"reoqrīao","type":"predicate","en":"___ is dusk."},
{"toaq":"sa","type":"quantifier","en":"existential quantifier"},
{"toaq":"sa póq","type":"argument phrase","en":"⁕somone⁕, ⁕somebody⁕"},
{"toaq":"sa rái","type":"argument phrase","en":"⁕something⁕"},
{"toaq":"sa túq rải","type":"argument phrase","en":"⁕all things (together)⁕"},
{"toaq":"sabāq","type":"predicate","en":"___ is soap."},
{"toaq":"sarālīa","type":"predicate","en":"___ is Australia."},
{"toaq":"saq","type":"predicate","en":"___ are three in number."},
{"toaq":"saqchīo","type":"predicate","en":"___ happens thrice / three times."},
{"toaq":"saqlīaq","type":"predicate","en":"___ is a triplet."},
{"toaq":"saqsīoq","type":"predicate","en":"___ is a tricycle."},
{"toaq":"sai","type":"interjection","en":"hello / hi / greetings"},
{"toaq":"sao","type":"predicate","en":"___ is big/large."},
{"toaq":"saodōaq","type":"predicate","en":"___ is a city."},
{"toaq":"saojēaq","type":"predicate","en":"___ grows / gets bigger."},
{"toaq":"su","type":"predicate","en":"___ are [previous predicate]."},
{"toaq":"suq","type":"predicate","en":"___ is you / the listener."},
{"toaq":"sua","type":"predicate","en":"___ is necessary for ___ to happen."},
{"toaq":"suahūaq","type":"predicate","en":"___ is superfluous / more than is necessary for ___ to happen."},
{"toaq":"suaq","type":"predicate","en":"___ sings."},
{"toaq":"sui","type":"predicate","en":"___ is least in property ___ among ___."},
{"toaq":"suo","type":"predicate","en":"___ is broken/inoperable."},

{"toaq":"sue","type":"predicate","en":"___ asks ___ to satisfy property ___."},
{"toaq":"suetā","type":"predicate","en":"___ is a sweater."},
{"toaq":"Sủe jí súq lî tủa nẻo ja dó máq tóqfūa ka.","type":"phrase","en":"⁕Please put it on the table⁕, ⁕I hereby ask you to put it on the table⁕"},

{"toaq":"suai","type":"predicate","en":"___ is fast/quick; ___ quickly does ___."},
{"toaq":"suaikūai","type":"predicate","en":"___ is in a hurry; ___ feels the urge to quickly satisfy property ___."},
{"toaq":"suaikōi","type":"predicate","en":"___ runs."},
{"toaq":"suao","type":"predicate","en":"___ is important."},
{"toaq":"suaojīe","type":"predicate","en":"___ cares about ___; ___ considers ___ important."},
{"toaq":"si","type":"predicate","en":"___ is attentive to / focuses on ___."},
{"toaq":"sidī","type":"predicate","en":"___ is a CD."},
{"toaq":"sigā","type":"predicate","en":"___ is a cigarette."},
{"toaq":"siq","type":"predicate","en":"___ is clean/pure."},
{"toaq":"siqkēa","type":"predicate","en":"___ is a washing mashine."},
{"toaq":"sia","type":"quantifier","en":"zero quantifier."},
{"toaq":"sia póq","type":"argument phrase","en":"⁕noone⁕"},
{"toaq":"sia rái","type":"argument phrase","en":"⁕nothing⁕"},
{"toaq":"siachōa","type":"predicate","en":"___ says nothing / is silent."},
{"toaq":"siaq","type":"predicate","en":"___ is to the right of ___."},
{"toaq":"siaqcū","type":"predicate","en":"___ moves rightwards."},
{"toaq":"siaqpāq","type":"predicate","en":"___ is the right part of ___."},
{"toaq":"siu","type":"predicate","en":"___ is similar to ___."},
{"toaq":"sio","type":"predicate","en":"___ is a thought/idea."},
{"toaq":"sioq","type":"predicate","en":"___ is a wheel."},
{"toaq":"sie","type":"predicate","en":"___ is following to ___ in sequence ___."},
{"toaq":"siefā","type":"predicate","en":"___ follows/goes after ___."},
{"toaq":"sieq","type":"predicate","en":"___ feels awe; ___ is amazed."},
{"toaq":"sieqcā","type":"predicate","en":"___ is amazing."},
{"toaq":"siai","type":"predicate","en":"___ is blood."},
{"toaq":"siao","type":"predicate","en":"___ is a beginning/start; ___ is a beginning/start of ___."},
{"toaq":"so","type":"illocution","en":"exclamation"},
{"toaq":"sokā","type":"predicate","en":"___ is soccer/football."},
{"toaq":"soq","type":"predicate","en":"___ is the ___est among ___; ___ is the most ___ among ___."},
{"toaq":"soq gỉ","type":"predicate","en":"___ is the best among ___."},
{"toaq":"soq hủi","type":"predicate","en":"___ is the worst among ___."},
{"toaq":"soq nủi","type":"predicate","en":"___ is the smallest among ___."},
{"toaq":"soq pủi","type":"predicate","en":"___ are the most numerous among ___."},
{"toaq":"soq sảo","type":"predicate","en":"___ is the biggest among ___."},
{"toaq":"soa","type":"predicate","en":"___ helps ___ to satisfy property ___."},
{"toaq":"soaq","type":"predicate","en":"___ is a garden."},

{"toaq":"soe","type":"predicate","en":"___ is sour."},
{"toaq":"se","type":"predicate","en":"___ is a result/product performing action ___."},
{"toaq":"sekūq","type":"predicate","en":"___ is a second."},

{"toaq":"sea","type":"predicate","en":"___ rests/relaxes."},
{"toaq":"seakūai","type":"predicate","en":"___ is exhausted."},
{"toaq":"seaq","type":"predicate","en":"___ has sex with ___; ___ has sexual intercourse with ___."},
{"toaq":"seo","type":"predicate","en":"___ is a spouse of ___."},
{"toaq":"seoq","type":"predicate","en":"___ is a sky."},
{"toaq":"seoqrēa","type":"predicate","en":"___ is a horizon."},
{"toaq":"sha","type":"predicate","en":"___ arrives at satisfying property ___."},
{"toaq":"shaq","type":"predicate","en":"___ is in front of ___."},
{"toaq":"shai","type":"predicate","en":"___ ceases to be the case; ___ stops satisfying property ___; ___ loses property ___."},
{"toaq":"shao","type":"predicate","en":"___ wants ___ to be the case."},
{"toaq":"shaogī","type":"predicate","en":"___ is good/virtuous."},
{"toaq":"shaohūi","type":"predicate","en":"___ is bad/evil/wicked."},
{"toaq":"shu","type":"predicatizer","en":"turn next phrase into quote predicate"},

{"toaq":"shua","type":"predicate","en":"___ falls to ___ from ___."},
{"toaq":"shuacāo","type":"predicate","en":"___ is autumn/fall."},
{"toaq":"shuaq","type":"predicate","en":"___ produces ___."},
{"toaq":"shuaqjīo","type":"predicate","en":"___ is a factory."},
{"toaq":"shuaqsē","type":"predicate","en":"___ is a product."},
{"toaq":"shui","type":"predicate","en":"___ is secret."},


{"toaq":"shue","type":"predicate","en":"___ remains/stays/keeps satisfying property ___."},
{"toaq":"shueq","type":"predicate","en":"___ is bitter."},
{"toaq":"shuai","type":"predicate","en":"___ is simple."},
{"toaq":"shuao","type":"predicate","en":"___ is a bird."},
{"toaq":"shi","type":"predicate","en":"___ are one in number."},
{"toaq":"shichīo","type":"predicate","en":"___ happens once / one time."},
{"toaq":"shiho","type":"predicate","en":"___ is him/her (singular)."},
{"toaq":"shirai","type":"predicate","en":"___ is an individual."},
{"toaq":"shiq","type":"predicate","en":"___ is olfactory; ___ pertains to the sese of smell/olfaction."},
{"toaq":"shiqgāi","type":"predicate","en":"___ smells ___."},
{"toaq":"shiqhūa","type":"predicate","en":"___ is a nose."},
{"toaq":"shia","type":"predicate","en":"___ is glass."},
{"toaq":"shiabīo","type":"predicate","en":"___ is a class (container)."},
{"toaq":"shiapōaqsē","type":"predicate","en":"___ is a glass shard; ___ is a piece of broken glass."},
{"toaq":"shiaq","type":"predicate","en":"___ is a leg."},
{"toaq":"shiu","type":"predicate","en":"___ is before / in the past of ___."},
{"toaq":"shiumē","type":"predicate","en":"___ is a/the past."},
{"toaq":"shiumejīo","type":"predicate","en":"___ is a museum."},
{"toaq":"shio","type":"predicate","en":"___ is a hip/shoulder."},

{"toaq":"shie","type":"predicate","en":"___ lets ___ happen; ___ allows ___ to happen."},
{"toaq":"shie","type":"predicate","en":"___ is awake."},



{"toaq":"sho","type":"predicate","en":"___ becomes such that they satisfy property ___."},

{"toaq":"shoa","type":"predicate","en":"___ is deep."},


{"toaq":"she","type":"predicate","en":"___ is the case if ___ is the case."},

{"toaq":"shea","type":"predicate","en":"___ is empty in aspect ___."},
{"toaq":"sheaq","type":"predicate","en":"___ stands on ___."},
{"toaq":"shei","type":"predicate","en":"___ is free to do ___."},
{"toaq":"sheo","type":"predicate","en":"___ regrets satisfying property ___."},
{"toaq":"sheokūq","type":"predicate","en":"___ says sorry to ___."},


{"toaq":"tama","type":"predicate","en":"___ is a tomato."},
{"toaq":"taq","type":"predicate","en":"___ is related to itself by property ___."},
{"toaq":"taq tủa mủaq","type":"predicate","en":"___ commits suicide / kills themselves."},
{"toaq":"tai","type":"predicate","en":"___ succeeds at satisfying property ___."},
{"toaq":"tao","type":"predicate","en":"___ does ___."},
{"toaq":"taodīe","type":"predicate","en":"___ advises ___ to do ___."},
{"toaq":"taokōe","type":"predicate","en":"___ chooses to do ___."},
{"toaq":"taomēq","type":"predicate","en":"___ considers doing ___."},
{"toaq":"taosīo","type":"predicate","en":"___ is an idea / a plan."},
{"toaq":"tu","type":"quantifier","en":"quantifier: universal quantifier"},
{"toaq":"tuchāo","type":"predicate","en":"___ is a bus/omnibus."},
{"toaq":"tuchāocē","type":"predicate","en":"___ is a bus stop."},
{"toaq":"tu póq","type":"argument phrase","en":"⁕everyone⁕"},
{"toaq":"tu rái","type":"argument phrase","en":"⁕everything⁕, ⁕anything⁕"},
{"toaq":"tuq","type":"predicate","en":"___ are all things that satisfy property ___."},
{"toaq":"tuqfīa","type":"predicate","en":"___ is first in sequence ___."},
{"toaq":"tuqsīe","type":"predicate","en":"___ is last in sequence ___."},
{"toaq":"tua","type":"predicate","en":"___ makes ___ happen."},
{"toaq":"tua bủo","type":"predicate","en":"___ prepares ___ for satisfying property ___."},
{"toaq":"tua dủa","type":"predicate","en":"___ tells ___ that ___ is the case; ___ makes ___ know ___."},
{"toaq":"tua dỉa","type":"predicate","en":"___ lowers ___ in how much it satisfies property ___."},
{"toaq":"tua gải","type":"predicate","en":"___ shows ___ object/event ___; ___ makes ___ observe ___."},
{"toaq":"tua hỏaq","type":"predicate","en":"___ ignites ___; ___ sets fire to ___."},
{"toaq":"tua jẻaq","type":"predicate","en":"___ raises ___ in how much it satisfies property ___."},
{"toaq":"tua jẻaq gẻa","type":"predicate","en":"___ raises ___ higher."},
{"toaq":"tua jẻaq nỉa","type":"predicate","en":"___ lowers ___ down."},
{"toaq":"tua kảqgāi","type":"predicate","en":"___ shows ___ object/event; ___ makes ___ see ___."},
{"toaq":"tua nỉe","type":"predicate","en":"___ puts ___ inside ___."},
{"toaq":"tua nẻo","type":"predicate","en":"___ puts ___ onto ___."},
{"toaq":"tua pỏaq","type":"predicate","en":"___ breaks/splits/separates ___."},
{"toaq":"tua sủo","type":"predicate","en":"___ breaks/destroys ___; ___ makes ___ be broken/inoperable."},
{"toaq":"tua shỉe","type":"predicate","en":"___ wakes ___ up; ___ awakens ___."},
{"toaq":"tua tỉ","type":"predicate","en":"___ puts ___ at ___."},
{"toaq":"tua tỉrīu","type":"predicate","en":"___ puts ___ back at ___."},

{"toaq":"tui","type":"predicate","en":"___ sits on ___."},
{"toaq":"tuifūa","type":"predicate","en":"___ is a chair/stool/seat/bench."},
{"toaq":"tuitōq","type":"predicate","en":"___ is a bench."},
{"toaq":"tuo","type":"predicate","en":"___ swallows; ___ swallows ____."},
{"toaq":"tuoq","type":"predicate","en":"___ is heavy."},
{"toaq":"tue","type":"predicate","en":"___ is a state / state of affairs / situation; ___ is a state of affairs of property ___."},

{"toaq":"tuai","type":"predicate","en":"___ is a body/corpse."},
{"toaq":"tuaibō","type":"predicate","en":"___ is physical/corporal."},
{"toaq":"tuaicīa","type":"predicate","en":"___ is non-physical."},
{"toaq":"tuao","type":"predicate","en":"___ is little/non-much in property ___."},
{"toaq":"tuaobū","type":"predicate","en":"___ is quite ___."},
{"toaq":"ti","type":"predicate","en":"___ is at ___."},
{"toaq":"tirīu","type":"predicate","en":"___ returns to location ___."},
{"toaq":"tibī","type":"predicate","en":"___ pertains to television."},
{"toaq":"tidūashō","type":"predicate","en":"___ finds ___; ___ discovers that ___ is at ___."},
{"toaq":"tijāo","type":"predicate","en":"___ is far away from ___."},
{"toaq":"tijūi","type":"predicate","en":"___ is near / in the vicinity of ___."},
{"toaq":"tinīqdūa","type":"predicate","en":"___ finds ___; ___ discovers that ___ is at ___."},
{"toaq":"tishā","type":"predicate","en":"___ arrives at ___."},
{"toaq":"tishūe","type":"predicate","en":"___ stays at ___."},

{"toaq":"tia","type":"predicate","en":"___ is behind ___."},
{"toaq":"tiaq","type":"predicate","en":"___ is the colour brown."},
{"toaq":"tiaqrēo","type":"predicate","en":"___ is of brown colour."},
{"toaq":"tio","type":"predicatizer","en":"predicatizer: how much; to what extent"},
{"toaq":"tiopūi","type":"predicate","en":"___ are how many."},
{"toaq":"tioq","type":"predicate","en":"___ is a lock."},
{"toaq":"tioqpōa","type":"predicate","en":"___ is locked."},
{"toaq":"tie","type":"predicate","en":"___ covers ___."},
{"toaq":"tiechūo","type":"predicate","en":"___ is a lid/cover."},
{"toaq":"tieq","type":"predicate","en":"___ is a way/path."},
{"toaq":"tiai","type":"predicate","en":"___ is a box."},
{"toaq":"tiao","type":"predicate","en":"___ matches/fits/suits ___ in property ___."},

{"toaq":"toq","type":"predicate","en":"___ is a board."},
{"toaq":"toqfūa","type":"predicate","en":"___ is a table."},
{"toaq":"toa","type":"predicate","en":"___ is a word."},
{"toaq":"toagīu","type":"predicate","en":"___ is a line (of text)."},
{"toaq":"toaq","type":"predicate","en":"___ is a language."},

{"toaq":"te","type":"predicate","en":"___ cuts ___ into ___."},
{"toaq":"techūo","type":"predicate","en":"___ is a knife."},
{"toaq":"teq","type":"predicate","en":"___ pays ___ to ___ for satisfying property ___."},
{"toaq":"teqgūai","type":"predicate","en":"___ does payed work ___; ___ does ___ as a job."},
{"toaq":"tea","type":"predicate","en":"___ is scared / experiences fear."},
{"toaq":"teaq","type":"predicate","en":"___ is a breast."},
{"toaq":"teaqjīeq","type":"predicate","en":"___ is a nipple."},
{"toaq":"teaqnīai","type":"predicate","en":"___ is a mammal."},
{"toaq":"teaqrīai","type":"predicate","en":"___ is a bra."},
{"toaq":"tei","type":"predicate","en":"___ is a form/shape; ___ is a form/shape of ___."},
{"toaq":"teo","type":"end-quote","en":"terminate full-text quote."},
{"toaq":"teoq","type":"predicate","en":"___ is a question."},
{"toaq":"teoqkūq","type":"predicate","en":"___ ask question ___ to ___."},
{"toaq":"teoqmōi","type":"predicate","en":"___ doubts that ___ is the case."},]
